name: Test

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Setup SSH Keys and known_hosts
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.ACCESS_KEY }}"

      - name: Install Dependencies
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: yarn install

      - name: Compile
        run: yarn compile

      - name: Test
        run: yarn test
